# Generated by Django 4.2.6 on 2023-11-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_company', models.CharField(max_length=150)),
                ('bike_name', models.CharField(max_length=150)),
                ('bike_fueltype', models.CharField(max_length=150)),
                ('bike_modelyear', models.CharField(max_length=150)),
            ],
        ),
    ]
